<a href="https://colab.research.google.com/github/angelocostantini/mnist-digits-recognition/blob/main/Digit_Recognition.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Setup:

In [ ]:
#pip install mnist

#Imports:

In [ ]:
from PIL import Image
import mnist
import numpy as np
import pandas as pd
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import confusion_matrix

#Training data:

In [ ]:
x_train = mnist.train_images()
y_train = mnist.train_labels()

#Testing data:

In [ ]:
x_test = mnist.test_images()
y_test = mnist.test_labels()

#Reshaping data:

We reshape the data as a matrix in order to pass them to the .fit() method.<br>
From a tensor made up by the matrixes of the pixels of the various images, we go to 

In [ ]:
x_train = x_train.reshape((-1, 28*28))
x_test = x_test.reshape((-1, 28*28))

#Preparing data for neural network:
A neural network requires inputs between 0 and 1:

In [ ]:
x_train = x_train / 256
x_test = x_test / 256
x_test[0]

#Neural Network instanciation:
Let's instanciate a neural network model for classification.<br>
As solver we use [ADAM](https://en.wikipedia.org/wiki/Stochastic_gradient_descent).<br>
As activation function for the hidden layers we use the [RELU](https://it.wikipedia.org/wiki/Rettificatore_(reti_neurali) function.<br>
We use two hidden layers of 64 neurons each:

In [ ]:
model = MLPClassifier(solver='adam', activation='relu', hidden_layer_sizes=(64, 64))

#Training:

In [ ]:
model.fit(x_train, y_train)

MLPClassifier(hidden_layer_sizes=(64, 64))

#Testing:

In [ ]:
y_pred = model.predict(x_test)
y_pred

array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

#Evaluating accuracy:

In [ ]:
accuracy = confusion_matrix(y_test, y_pred)
accuracy

array([[ 972,    0,    2,    0,    0,    0,    1,    1,    3,    1],
       [   0, 1121,    2,    2,    0,    0,    4,    1,    5,    0],
       [   5,    2, 1004,    2,    2,    0,    2,    6,    8,    1],
       [   0,    0,    5,  991,    2,    3,    0,    3,    4,    2],
       [   0,    1,    3,    2,  955,    0,    6,    2,    0,   13],
       [   2,    0,    1,    9,    1,  865,    4,    1,    7,    2],
       [   4,    2,    2,    0,    3,    6,  940,    0,    1,    0],
       [   2,    1,   11,    3,    2,    0,    1, 1000,    1,    7],
       [   4,    1,    2,    6,    3,    3,    1,    3,  948,    3],
       [   1,    3,    0,    7,    9,    5,    0,    3,    2,  979]])

In [ ]:
model.predict([x_test[0]]) == y_test[0]

array([ True])

#Open my images:

In [ ]:
def image_to_pixels(img_path):
  img = Image.open(img_path).convert('L')
  img_pixels = np.array(img.getdata())
  return img_pixels / 256

In [ ]:
my_number = image_to_pixels('my_number.png')
p = model.predict([my_number])
p

array([9], dtype=uint8)